version: '3'

volumes:
  studentrant_1_db:
  studentrant_1_configdb:
  studentrant_2_db:
  studentrant_2_configdb:
  studentrant_3_db:
  studentrant_3_configdb:
  studentrant_server_test:

services:
  sr-mongo1:
    hostname: mongo1
    container_name: studentrant-mongo-node-1
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "studentrant", "--journal", "--dbpath", "/data/db"]
    volumes:
      - studentrant_1_db:/data/db
      - studentrant_1_configdb:/data/configdb
    depends_on:
      - sr-mongo2
      - sr-mongo3

  sr-mongo2:
    hostname: mongo2
    container_name: studentrant-mongo-node-2
    image: mongo
    expose:
      - 27017
    ports:
      - 27018:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "studentrant", "--journal", "--dbpath", "/data/db"]
    volumes:
      - studentrant_2_db:/data/db
      - studentrant_2_configdb:/data/configdb

  sr-mongo3:
    hostname: mongo3
    container_name: studentrant-mongo-node-3
    image: mongo
    expose:
      - 27017
    ports:
      - 27019:27017
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "studentrant", "--journal", "--dbpath", "/data/db"]
    volumes:
      - studentrant_3_db:/data/db
      - studentrant_3_configdb:/data/configdb

  elk-stack:
    hostname: elk
    image: sebp/elk
    network_mode: host
    volumes:
      - ../.elk-stack/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml:ro
    expose:
      - 5601
      - 9200
      - 5044
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044

  filebeat:
    hostname: filebeat
    network_mode: host
    image: docker.elastic.co/beats/filebeat-oss:7.9.1
    user: root
    environment:
      - setup.kibana.host=5601
      - output.elasticsearch.hosts=["localhost:9200"]
    volumes:
      - "../.elk-stack/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../scripts/filebeat.sh:/usr/share/filebeat/filebeat.sh:ro"
    entrypoint: ["bash", "./filebeat.sh"]
