name: test
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2

      - name: install yarn
        run: npm install -g yarn

      - name: install packages
        run: yarn install

      - name: edit /etc/hosts
        run: echo "0.0.0.0 localhost mongo1 mongo2 mongo3" | sudo tee -a /etc/hosts

      - name: cat /etc/hosts
        run: sudo cat /etc/hosts

      - name: Run Test
        run: yarn test
